# Autogenerated wrapper script for ProtocolBuffersLite_jll for i686-w64-mingw32-cxx11
export libprotobuf_lite

using CompilerSupportLibraries_jll
using Zlib_jll
JLLWrappers.@generate_wrapper_header("ProtocolBuffersLite")
JLLWrappers.@declare_library_product(libprotobuf_lite, "libprotobuf-lite.dll")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, Zlib_jll)
    JLLWrappers.@init_library_product(
        libprotobuf_lite,
        "bin\\libprotobuf-lite.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
