# Autogenerated wrapper script for ProtocolBuffersLite_jll for x86_64-apple-darwin
export libprotobuf_lite

using CompilerSupportLibraries_jll
using Zlib_jll
JLLWrappers.@generate_wrapper_header("ProtocolBuffersLite")
JLLWrappers.@declare_library_product(libprotobuf_lite, "@rpath/libprotobuf-lite.3.16.1.0.dylib")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, Zlib_jll)
    JLLWrappers.@init_library_product(
        libprotobuf_lite,
        "lib/libprotobuf-lite.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
